fail_fast: false
default_language_version:
  python: python3
default_stages:
  - commit
  - push
minimum_pre_commit_version: 3.0.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
      - id: check-added-large-files
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.6.3
    hooks:
      - id: nbqa-pyupgrade
        args: [--py38-plus]
      - id: nbqa-black
      - id: nbqa-isort
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        types_or: [yaml]
