[tool.isort]
profile = "black"
include_trailing_comma = true
multi_line_output = 3
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "NUMERIC", "PLOTTING", "BIO", "FIRSTPARTY", "LOCALFOLDER"]
# also contains what we import in notebooks
known_numeric = ["numpy", "scipy", "pandas", "sklearn", "networkx"]
known_bio = ["anndata", "scanpy", "squidpy"]
known_plotting = ["IPython", "matplotlib", "mpl_toolkits", "seaborn"]

[tool.tox]
legacy_tox_ini = """
    [tox]
    min_version = 4.0
    env_list = lint

    [testenv:lint]
    description = Lint the notebooks.
    deps = pre-commit>=3.0.0
    skip_install = true
    commands =
        pre-commit run --all-files --show-diff-on-failure
"""
